import type { Actor } from './api'

const PERMISSIONS: Record<string, string[]> = {
  admin: [
    'user:read',
    'user:write',
    'user:delete',
    'company:read',
    'company:write',
    'company:delete',
    'contact:read',
    'contact:write',
    'contact:delete',
    'lead:read',
    'lead:write',
    'lead:delete',
    'activity:read',
    'activity:write',
    'activity:delete',
    'task:read',
    'task:write',
    'task:delete',
    'opportunity:read',
    'opportunity:write',
    'opportunity:delete',
    'pipeline:read',
    'pipeline:write',
    'pipeline:delete',
    'campaign:read',
    'campaign:write',
    'campaign:delete',
    'follow-up:read',
    'follow-up:write',
    'follow-up:delete',
    'analytics:read',
    'contributor:read',
    'contributor:write',
    'contributor:delete',
    'partner:read',
    'partner:write',
    'partner:delete',
    'community:read',
    'community:write',
    'community:delete',
    'investor:read',
    'investor:write',
    'investor:delete',
    'use-case:read',
    'use-case:write',
    'use-case:delete',
    'audit:read',
    'dashboard:read',
  ],
  manager: [
    'user:read',
    'company:read',
    'company:write',
    'contact:read',
    'contact:write',
    'contact:delete',
    'lead:read',
    'lead:write',
    'lead:delete',
    'activity:read',
    'activity:write',
    'activity:delete',
    'task:read',
    'task:write',
    'task:delete',
    'opportunity:read',
    'opportunity:write',
    'opportunity:delete',
    'pipeline:read',
    'campaign:read',
    'campaign:write',
    'campaign:delete',
    'follow-up:read',
    'follow-up:write',
    'follow-up:delete',
    'analytics:read',
    'contributor:read',
    'contributor:write',
    'contributor:delete',
    'partner:read',
    'partner:write',
    'partner:delete',
    'community:read',
    'community:write',
    'community:delete',
    'investor:read',
    'investor:write',
    'investor:delete',
    'use-case:read',
    'use-case:write',
    'use-case:delete',
    'audit:read',
    'dashboard:read',
  ],
  member: [
    'company:read',
    'contact:read',
    'contact:write',
    'lead:read',
    'activity:read',
    'activity:write',
    'task:read',
    'task:write',
    'opportunity:read',
    'pipeline:read',
    'campaign:read',
    'follow-up:read',
    'follow-up:write',
    'analytics:read',
    'contributor:read',
    'partner:read',
    'community:read',
    'investor:read',
    'use-case:read',
    'dashboard:read',
  ],
}

export function can(actor: Actor | null, resource: string, action: string): boolean {
  if (!actor) return false
  const permission = `${resource}:${action}`
  return actor.roles.some((role) => (PERMISSIONS[role.toLowerCase()] ?? []).includes(permission))
}

export function isMemberOnly(actor: Actor | null): boolean {
  if (!actor) return false
  return !actor.roles.some((role) => role.toLowerCase() === 'admin' || role.toLowerCase() === 'manager')
}